### ISSUE TITLE
Migration for 2.0.0 breaking changes

### ISSUE THREAD

**Issue by kwonoj** [Durzn/BracketHighlighter#10]
Just updated to 2.0.0 and see different behavior between same config:

1.8.1

![image](https://user-images.githubusercontent.com/1210596/85209982-38524680-b2f1-11ea-9eb4-f3b22e8fd05a.png)

2.0.0

![image](https://user-images.githubusercontent.com/1210596/85209987-3d16fa80-b2f1-11ea-9002-e48ac57a76ab.png)

I'd like to preserve existing behavior, but hard to find what config should be adjusted. Is there some instructions, or way to migrate configs?

current configs are like below:

```
  "BracketHighlighter.textDecoration": "none",
  "BracketHighlighter.reverseSearchEnabled": true,
  "BracketHighlighter.letterSpacing": "0px",
  "BracketHighlighter.fontStyle": "none",
```

**Comment by Durzn** [comment]
Hi, to remove the color of your parentheses please add the following line to your config:
"BracketHighlighter.textColor": ""
Sorry for the confusion, this was set to be a new default parameter, so when initially downloading the extension people don't have such an aggressive highlighting.

**Comment by kwonoj** [comment]
And how to set inner text to bold?

**Comment by Durzn** [comment]
To make the text bold use this line:
"BracketHighlighter.fontWeight": "bold"
Also, to make sure that the text inside is highlighted add this line:
"BracketHighlighter.ignoreContent": false

**Comment by kwonoj** [comment]
Thanks for the quick help, that resolves thing for me.

Appreciate for great plugin also, this is one I could not live without daily.
