### ISSUE TITLE
Can't do multi matches? (Not sure what word to use)

### ISSUE THREAD

**Issue by CrabBucket** [Durzn/BracketHighlighter#12]
I was doing some C programming and I wanted to make the brackets `"BracketHighlighter.customSymbols": [

        {

                  "open": "pthread_mutex_lock",

                  "close": "pthread_cond_wait",

        },

        {

               "open": "pthread_mutex_lock",

               "close": "pthread_mutex_unlock",

        }

      ]`
And I wanted it to match the mutex lock to either the conditional wait or the unlock (both of which unlock the mutex) How ever it just makes the first one take precedent and disregards the second.  My proposed solution would either add an option to do this or just allow someone to write what I just did and have it work how I think it should.

**Comment by CrabBucket** [comment]
Just looked back into your settings and saw you have a Regex enabled mode but im very bad with regex and don't want to learn :P

**Comment by Durzn** [comment]
Hi, I'll have a look at it. The Regex mode is not suitable for this feature, it's supposed to ignore escaped characters when enabled.

**Comment by Durzn** [comment]
Added with commit 5f09d4002561dca060c41dd11f207ca7239e13af. I'll get it to the marketplace in the coming days.

**Comment by Durzn** [comment]
Released as part of version 2.2.0.
