### ISSUE TITLE
Too Saturated

### ISSUE THREAD

**Issue by ohlawdie** [Durzn/BracketHighlighter#15]
Love the extension, how can I change the green color that affects the brackets / symbols?

**Comment by Durzn** [comment]
Hi, thanks for your kind words.
You can change the color with the "Text Color" setting.
You can simply use hex values of the color you want (I use `#FF0000` for a red tone) 
If you prefer to use the json file heres an example:
"BracketHighlighter.textColor": "#FF0000"

**Comment by ohlawdie** [comment]
Oh geez @Durzn , I don't know how I missed that. Thanks! I guess while we're here..do you mind answering what BracketHighlighter.text is meant to handle just out of curiousity? Will that change a font-family or is it just for language-server specific reasons?

**Comment by Durzn** [comment]
BracketHighlighter.text has no functionality, it is only a block of text for the settings. Sadly it clutters the settings.json file, which I hadn't thought of when initially creating it.

**Comment by ohlawdie** [comment]
No problem, thank you for your help!
