### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by sebthom** [Durzn/BracketHighlighter#17]
Please submit your extension to the [Open VSX](https://open-vsx.org/) registry/marketplace.

This way it can be legally downloaded/installed in opensource builds/forks of VSCode, e.g. VSCodium and Eclipse [Theia](https://theia-ide.org/).

FAQs: https://www.eclipse.org/legal/open-vsx-registry-faq/

Thanks!

**Comment by Durzn** [comment]
I'll look into it, thanks for the information.

**Comment by Durzn** [comment]
The extension was published here: https://open-vsx.org/extension/Durzn/brackethighlighter
Its namespace has not yet been claimed, but hopefully will be soon.

**Comment by sebthom** [comment]
Thank you!!!

**Comment by Durzn** [comment]
Namespace has been claimed.
