### ISSUE TITLE
Enable highlighting when cursor is anywhere in the scope

### ISSUE THREAD

**Issue by yani** [Durzn/BracketHighlighter#2]
Great extension. I use it only for blurring out the rest of the scopes, so only the current scope is highlighted. 

Would it be possible to add a setting to enable this highlighting when the cursor is anywhere in the scope?

Regards

**Comment by Durzn** [comment]
I'll look into it, however determining which scope a line of code belongs to isn't trivial without a known starting point and will have bad performance. I'll try my best though.

**Comment by Durzn** [comment]
Added this with commit 6d1a03c
This is now available in version 1.3.0
