### ISSUE TITLE
This extension is not working in vscode 1.66.0

### ISSUE THREAD

**Issue by hanniballecter86** [Durzn/BracketHighlighter#21]
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Durzn** [comment]
Hi, I‘ll need to take a closer look at this when I have time. It works fine one my machine where only the Windows version slightly differs from yours. Did the extension work for you in earlier releases of vscode?

**Comment by hanniballecter86** [comment]
Yes, it works like a charm before I update my vscode to the latest version recently.

**Comment by hanniballecter86** [comment]
> Hi, I‘ll need to take a closer look at this when I have time. It works fine one my machine where only the Windows version slightly differs from yours. Did the extension work for you in earlier releases of vscode?

Hey, I just found out that I didn't toggle the extension. It might be disabled automatically when I upgrade vscode. Sorry for the bother :(.

By the way, I had `"BracketHighlighter.enableExtension": true` in my setting.json, while it looks like Ctrl + Alt + L hot key still takes the privilidge?

**Comment by Durzn** [comment]
Glad to hear it's still working for you. The hotkey is unfortunately enabled by default, but changing default values at this point might be frustrating for users, so I'll leave it as it is.
However, if you don't like it you can just disable it in the vscode hotkey settings.
