### ISSUE TITLE
Border around text not working(?)

### ISSUE THREAD

**Issue by Johsnon** [Durzn/BracketHighlighter#23]
Hi,
I want to achieve the red border outlining the text as you show in the example
https://github.com/Durzn/BracketHighlighter/blob/master/assets/border.gif
![image](https://github.com/Durzn/BracketHighlighter/blob/master/assets/border.gif)
but I cannot get it to work.
For me it looks like this:
![grafik](https://user-images.githubusercontent.com/8524607/196674395-3f101cc1-6391-424e-a7d5-23586d9f8a61.png)

I am currently using v2.3.1 (installed via VS Code Marketplace)

Do you know what is going wrong? 🤔

**Comment by Durzn** [comment]
Hi, could you check if the "Ignore Content" option is checked? In your image it looks like only the parentheses are highlighted, which might mean that it's checked. That option will apply the settings only to your symbols, not to the text within.

**Comment by Johsnon** [comment]
yes - that was it!
thank you very much 😅

**Comment by Durzn** [comment]
Glad that was it. Thanks for using the extension :)
