### ISSUE TITLE
Feature request: Changing Brackets Style

### ISSUE THREAD

**Issue by lorens-osman-dev** [Durzn/BracketHighlighter#24]
Hi ,
Is there any way i can changing brackets style to custom  style, this will be nice in my opinion. 
thanks , have a nice day .

![20221223_030653](https://user-images.githubusercontent.com/114411575/209245637-edf041e2-6032-4ef0-91bc-daa268abd90b.jpg)

**Comment by Durzn** [comment]
Hi, thank you for the suggestion. 
I'm not really sure how these brackets can be used. Are they some kind of special font?
Unfortunately changing fonts is not possible as the API used (https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions) does not allow such things or anything comparable. Also it would be hard to differentiate between actual brackets and custom symbols the user may or may not use.

If you just want to have these brackets, maybe it would be best to create your own font where you just replace the brackets with the ones you posted? Not sure if the effort is worth it for you, but I'm afraid this can't be solved within this extension.
