### ISSUE TITLE
Feature request: Add configure for highlight bracket pair only when put cursor outside bracket

### ISSUE THREAD

**Issue by coder054** [Durzn/BracketHighlighter#25]
I want something like drracket editor, when I put the cursor outside of open bracket or outside of closing bracket, I get get syntax highlighting, but I don't want syntax highlighting when the cursor inside brackets
![image](https://user-images.githubusercontent.com/13082466/230341652-bf51bcea-ca39-4c2c-b6b6-c83e8bf38aac.png)
![image](https://user-images.githubusercontent.com/13082466/230341820-2eecacc7-7f94-406c-acf6-55a7fdb39e85.png)
![image](https://user-images.githubusercontent.com/13082466/230343158-3354a9d5-71c8-49da-afa1-42bc2c0b1df8.png)
Thank you for very nice extension!

**Comment by Durzn** [comment]
Hi, I'm glad you like the extension and thank you for your suggestion. 
I'll look into it when I have some spare time, but I'm afraid that could be a while, as the extension is no longer a priority of mine.

**Comment by Durzn** [comment]
Hi @coder054 , not sure if you are still interested in this feature, but I added it in the following merge request: https://github.com/Durzn/BracketHighlighter/pull/31
It's not publicly available in the store yet, as this is a pretty big overhaul of the extension and I wanted to add some tests, but the implementation itself is done. So feel free to check it out if you feel like it.

**Comment by Durzn** [comment]
Closed, added with version 3.0.0
