### ISSUE TITLE
2.4.0 performance issue

### ISSUE THREAD

**Issue by Kotsuha** [Durzn/BracketHighlighter#29]
On my computer, after updating to `2.4.0`, the performance is worse than `2.3.2`. When I'm moving my cursor, it lags.

I've tried to debug and have found a possible reason. It seems the array `bracketHighlightGlobals.decorationTypes` is getting larger and larger. Therefore, whenever `removePreviousDecorations()` is called, it takes longer time. This issue doesn't exist in `2.3.2`.

### How to examine

1. Clone [my fork](https://github.com/Kotsuha/BracketHighlighter) and check out the `test` branch. This is based on `2.4.0`. The only difference is:
    * Some added logs.
    * You can press <kbd>ctrl+alt+\\</kbd> to clear the array.

2. Use VS Code to open the project. Press <kbd>F5</kbd> to start debugging.

    My user settings is empty:

    ```
    {
    }
    ```

    My test txt file:

    ```
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    ```

    Hold <kbd>down</kbd> and then hold <kbd>up</kbd>. Do this several times. See the logs. You can see the array becomes larger. On my computer, the cursor starts lagging significantly when the array length hits around 300.

    ![bracket-highlighter-fork-issue-demo-2](https://github.com/Durzn/BracketHighlighter/assets/10438710/7e455a82-c251-4764-a614-52987b192bc8)

**Comment by Durzn** [comment]
Hi, thanks for bringing that up! Could you try running this pull request on your machine (or just try the attached vsix file by installing it)?
https://github.com/Durzn/BracketHighlighter/pull/30
This should fix the issue
[brackethighlighter-2.4.1.vsix.zip](https://github.com/Durzn/BracketHighlighter/files/12333824/brackethighlighter-2.4.1.vsix.zip)

**Comment by Durzn** [comment]
Thanks for the detailed error report, it should be fixed now and the new version is published. If you still feel performance issues feel free to comment again :)
