### ISSUE TITLE
v.3.0.0 skips over closing symbol

### ISSUE THREAD

**Issue by ktekinay** [Durzn/BracketHighlighter#32]
First, thanks for putting the work into this. I am trying it out and found that it seems to skip over the closing symbol.

These are my settings:

```
  "BracketHighlighter.customSymbols": [
    {
      "highlightPair": [
        {
            "symbol": "\\bfn ",
            "isRegex": true,
            "canBeSubstring": false
        },
        {
            "symbol": "\\bend\\b",
            "isRegex": true,
            "canBeSubstring": false
        },
      ]
    },
    {
      "highlightPair": [
        {
            "symbol": "\\bdo\\b(?!:)",
            "isRegex": true,
            "canBeSubstring": true
        },
        {
            "symbol": "\\bend\\b",
            "isRegex": true,
            "canBeSubstring": true
        },
      ]
    },

    // {"open": "do:", "close": ""},
    // {"open": "do", "close": "end"},
  ],
  "BracketHighlighter.backgroundColor": "lightyellow",
  "BracketHighlighter.textColor": "",
  "BracketHighlighter.differentSymbolHighlightingUsed": true,
  "BracketHighlighter.backgroundColorSymbol": "yellow",
  "BracketHighlighter.textColorSymbol": "",
  "BracketHighlighter.fontWeightSymbol": "bold",
```

Give this code, nothing is highlighted:

```
defmodule Something do


end
```

If I add a function, it misses the first `end` and highlights the second:

```
defmodule Something do
  def my_function do # highlighting here...
    nil
  end
end # ...matches here
```

**Comment by ktekinay** [comment]
In my experimentation, I see that I uncommented that first pair, but this fails too:

```
  "BracketHighlighter.customSymbols": [
    // {
    //   "highlightPair": [
    //     {
    //         "symbol": "\\bfn ",
    //         "isRegex": true,
    //         "canBeSubstring": false
    //     },
    //     {
    //         "symbol": "\\bend\\b",
    //         "isRegex": true,
    //         "canBeSubstring": false
    //     },
    //   ]
    // },
    {
      "highlightPair": [
        {
            "symbol": "\\bdo\\b(?!:)",
            "isRegex": true,
            "canBeSubstring": true
        },
        {
            "symbol": "\\bend\\b",
            "isRegex": true,
            "canBeSubstring": true
        },
      ]
    },

    // {"open": "do:", "close": ""},
    // {"open": "do", "close": "end"},
  ],
```

**Comment by Durzn** [comment]
Huh, weird that such a basic use case doesn‘t work for you. I actually added multiple tests that should cover more than just that.
I‘ll take a look at the problem later.
Thanks for trying it out!

**Comment by Durzn** [comment]
Should be fixed in 3.0.1, I added another test to cover this scenario.

**Comment by ktekinay** [comment]
So far, so good, thanks.

**Comment by ktekinay** [comment]
And I solved my issue with two different keywords using the same closing "symbol" by combining into one pattern.

In Elixir, you can have a do/end block or a  fn/end block. I changed settings to this and it seems to work.

```
    {
      "highlightPair": [
        {
            "symbol": "\\b(do\\b(?!:)|fn\\b)",
            "isRegex": true,
            "canBeSubstring": true
        },
        {
            "symbol": "\\bend\\b",
            "isRegex": true,
            "canBeSubstring": true
        },
      ]
    },
```

Maybe that should be a note in the documentation?

I know I've said it before, but I truly appreciate your work on this.

**Comment by Durzn** [comment]
Glad to hear that! I've found one other weird interaction during my working day, but other than that it seemed to work quite well, I guess it will be fully released within the next week.

Thanks for the reminder, I intended to add that information to the README, but forgot about it.

Thanks for the kind words, interactions with people like you really keep me going!

**Comment by ktekinay** [comment]
Just got v.3.0.3 and still working great in my use case, so I'm closing this issue.
