### ISSUE TITLE
add `do...end` for ruby (and potentially other languages)

### ISSUE THREAD

**Issue by ngouy** [Durzn/BracketHighlighter#4]
Awesome extension thank you :)

Though do you think it can be possible to enable it for other kinds of blocks (such as, in this case, `do ... end` blocks in ruby

**Comment by Durzn** [comment]
I'll look into it.

**Comment by Durzn** [comment]
Added the possibility to use user defined opening and closing symbols with commit  0187baa . Please use those for your use case. This is available starting with version 1.4.0.

**Comment by ngouy** [comment]
ty 👍
