### ISSUE TITLE
[Features Request] Only highlight custom symbol

### ISSUE THREAD

**Issue by idr4n** [Durzn/BracketHighlighter#6]
Hi,
I was trying your extension, and looks quite good, Thank you!

I was wondering if there is any setting in which the extension only highlights the symbols, but not the text in between? I looked for such a setting but couldn't find it.

This extension is quite handy for languages such Elixir or Ruby (with do...end), and like in Sublime's Brackethighlighter, i just want the symbols to be highlighted.

Another thing, it would be great if you add a command to be able to select text within the symbols, and also a command to jump back and forth from opening to closing symbol.

Thanks in advance and take care!

**Comment by Durzn** [comment]
Hi,
thanks for using the extension. I'll look into adding the option to only highlight the brackets.
Performing commands or other kinds of tasks within the brackets is outside the scope of this extension I'm afraid.

**Comment by Durzn** [comment]
Feature not to highlight text between symbols has been added with commit b132c37
It's available in version 1.7.0

**Comment by Durzn** [comment]
I added the possibility to jump to/out of symbols and to select the text inside of symbols. This is available from version 2.0.0
