### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by paul-f-maxson** [Durzn/BracketHighlighter#8]
Add a transitionDuration property so the change can fade in and out.

[This JSBin](https://jsbin.com/cesoyizoda/1/edit?html,output) demonstrates the required code

**Comment by paul-f-maxson** [comment]
I'd be happy to tackle this if I can find some time around finishing up my semester.

**Comment by paul-f-maxson** [comment]
Well I completed the implementation but then I realized that vscode doesn't support transition-time. Shucks.

**Comment by Durzn** [comment]
I tried the same yesterday, I'll keep this in mind if they ever add it.
Thanks for your initiative though!
