### ISSUE TITLE
[Feature Request] Rainbow Brackets

### ISSUE THREAD

**Issue by Stanzilla** [Durzn/BracketHighlighter#9]
Would love to see an option akin to https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2 that colors the brackets differently.

**Comment by Durzn** [comment]
Added this with commit 854ca46
This feature will be available from version 1.8.0.

Please note that this changes the color of all the highlighted text. If you want it to only color the brackets you will have to enable the option "ignoreContent".

**Comment by Stanzilla** [comment]
Oh my, you are fast! Thank you so much!
